-- Add size (w,h) and style (e.g. fontSize) JSONB columns to visual entities
ALTER TABLE IF EXISTS highlights
  ADD COLUMN IF NOT EXISTS size JSONB,
  ADD COLUMN IF NOT EXISTS style JSONB;

ALTER TABLE IF EXISTS themes
  ADD COLUMN IF NOT EXISTS size JSONB,
  ADD COLUMN IF NOT EXISTS style JSONB;

ALTER TABLE IF EXISTS insights
  ADD COLUMN IF NOT EXISTS size JSONB,
  ADD COLUMN IF NOT EXISTS style JSONB;

ALTER TABLE IF EXISTS annotations
  ADD COLUMN IF NOT EXISTS size JSONB,
  ADD COLUMN IF NOT EXISTS style JSONB;
