-- This migration has been superseded by 010_add_project_to_themes_insights.sql
-- Kept as a no-op so existing installs that already applied this filename are unaffected.
-- New installs will apply 010_ instead.
